- name: setting up appache webserver on ubuntu clients
  hosts:  ubuntu-client
 
  tasks:
    - name: update  all packages # equivalent to yum update -y
      ansible.builtin.apt:
        name: '*' # should that mean we want to update any single packages
        state: latest
 
    - name: Update package information
      ansible.builtin.apt:
        update_cache: True
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems
 
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems
 
    - name: Start service httpd, if not started # systemctl httpd# systemctl httpd
      ansible.builtin.service:
        name: apache2
        state: started
 
    - name: Start service httpd on boot # systemctl enable httpd
      ansible.builtin.service: #service module
        name: apache2
        enabled: true
 
    - name: Copy index.html file from the controller to the target hosts
      ansible.builtin.copy: # service module
        src: /home/ubuntu/index.html #controller 
        dest: /var/www/html  # target server (clients)       